export const REQUEST_FOR_CURRENT_USER = "REQUEST_FOR_CURRENT_USER";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_FAILURE = "FETCH_CURRENT_USER_FAILURE";
export const LOGOUT = "LOGOUT";
