export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const FETCH_ALL_ASSOCIATED_POST = "FETCH_ALL_ASSOCIATED_POST";
export const FETCH_ALL_ASSOCIATED_POST_SUCCESS =
  "FETCH_ALL_ASSOCIATED_POST_SUCCESS";
export const FETCH_ALL_ASSOCIATED_POST_FAILURE =
  "FETCH_ALL_ASSOCIATED_POST_FAILURE";
export const RESET_CONTACT = "RESET_CONTACT";
